#!/usr/bin/env ruby
# vim:fileencoding=utf-8

exe = "#{ENV['GOPATH'].split(':').first}/bin/artifacts"
$stdout.puts(
  $stdin.read.sub(/___USAGE___/, `#{exe} help 2>&1`.chomp)
             .sub(/___UPLOAD_USAGE___/, `#{exe} help upload 2>&1`.chomp)
)
