#!/bin/bash

set -e

SHA256SUMMER=sha256sum
if ! sha256sum --version >/dev/null 2>&1 ; then
  SHA256SUMMER=gsha256sum
fi

export ARTIFACTS_PATHS="$(git ls-files -o | tr "\n" ":"):SHA256SUMS"
$SHA256SUMMER ${ARTIFACTS_PATHS//:/ } > SHA256SUMS

echo "  TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
echo "  TRAVIS_BRANCH=$TRAVIS_BRANCH"
echo "  TRAVIS_GO_VERSION=$TRAVIS_GO_VERSION"

if [[ $TRAVIS_PULL_REQUEST == 'false' ]] &&
   [[ $TRAVIS_BRANCH == 'master' ]] &&
   [[ $TRAVIS_GO_VERSION == 'go1.2.2' ]] ; then
  echo "Deploying as 'stable'"
  export ARTIFACTS_TARGET_PATHS="$ARTIFACTS_TARGET_PATHS:artifacts/stable"
else
  echo "Not deploying as 'stable'"
fi

echo "  ARTIFACTS_TARGET_PATHS=$ARTIFACTS_TARGET_PATHS"
exec ${GOPATH%%:*}/bin/artifacts upload
