#!/bin/bash

set -e

SHA256SUMMER=sha256sum
if ! sha256sum --version &>/dev/null ; then
  SHA256SUMMER=gsha256sum
fi

export ARTIFACTS_PATHS="$(
  git ls-files -o | grep -v '\.deps' | tr "\n" ":"
):SHA256SUMS"
$SHA256SUMMER ${ARTIFACTS_PATHS//:/ } > SHA256SUMS

echo "    TRAVIS_BRANCH=\"$TRAVIS_BRANCH\""
echo "    TRAVIS_GO_VERSION=\"$TRAVIS_GO_VERSION\""
echo "    TRAVIS_PULL_REQUEST=\"$TRAVIS_PULL_REQUEST\""
echo "    TRAVIS_TAG=\"$TRAVIS_TAG\""

if [[ "x$TRAVIS_BRANCH" == "xmaster" ]] &&
   [[ "x$TRAVIS_GO_VERSION" == "x1.13.5" ]] &&
   [[ "x$TRAVIS_PULL_REQUEST" == "xfalse" ]] &&
   [[ "x$TRAVIS_TAG" == "x" ]] ; then
  echo "    # Deploying as 'stable'"
  export ARTIFACTS_TARGET_PATHS="$ARTIFACTS_TARGET_PATHS:artifacts/stable"
else
  echo "    # Not deploying as 'stable'"
fi

echo "    ARTIFACTS_TARGET_PATHS=$ARTIFACTS_TARGET_PATHS"
exec ${GOPATH%%:*}/bin/artifacts upload
