#!/bin/bash

set -e

cp -v ${GOPATH%%:*}/bin/artifacts ./artifacts
export ARTIFACTS_PATHS="$(git ls-files -o | tr "\n" ";")"
sha256sum ${ARTIFACTS_PATHS//;/ } > SHA256SUMS
export ARTIFACTS_PATHS="$(git ls-files -o | tr "\n" ";")"

echo "  TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
echo "  TRAVIS_BRANCH=$TRAVIS_BRANCH"
echo "  TRAVIS_GO_VERSION=$TRAVIS_GO_VERSION"

if [[ $TRAVIS_PULL_REQUEST == 'false' ]] &&
   [[ $TRAVIS_BRANCH == 'master' ]] &&
   [[ $TRAVIS_GO_VERSION == 'go1.2.2' ]] ; then
  echo "Deploying as 'stable'"
  export ARTIFACTS_TARGET_PATHS="$ARTIFACTS_TARGET_PATHS;artifacts/$(go env GOOS)/$(go env GOARCH)/$TRAVIS_REPO_SLUG/stable"
else
  echo "Not deploying as 'stable'"
fi

${GOPATH%%:*}/bin/artifacts upload
