#!/bin/bash

set -e

ARTIFACTS_DEST=${ARTIFACTS_DEST:-$HOME/bin/artifacts}

mkdir -p $(dirname "$ARTIFACTS_DEST")
curl -sL -o "$ARTIFACTS_DEST" \
  https://s3.amazonaws.com/meatballhat/artifacts/linux/amd64/meatballhat/artifacts/stable/artifacts
chmod +x "$ARTIFACTS_DEST"
PATH="$(dirname "$ARTIFACTS_DEST"):$PATH" artifacts -v
