#!/bin/bash

export ARTIFACTS_TARGET_PATHS="artifacts/$(go env GOOS)/$(go env GOARCH)/meatballhat/master;artifact/$(go env GOOS)/$(go env GOARCH)/meatballhat/stable"
export ARTIFACTS_CONCURRENCY=3
export ARTIFACTS_RETRIES=1
export ARTIFACTS_PATHS="$(git ls-files -o | grep -v '.env' | tr "\n" ";")"
export PATH="${GOPATH%%:*}/bin:$PATH"

exec artifacts ${CMD:-upload} "$@"
